In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

import json
import pickle

import matplotlib.pyplot as plt
import seaborn as sns



In [ ]:
1.Problem Statement 
to predict values medical insurance on the basis of age,gender,bmi,children,region,charges



In [ ]:
2.Data Gathering

In [4]:
df=pd.read_csv("C:\priya python\python learning\linear regression\medical_prediction\MedicalInsurancePredictor\Data\medical_insurance.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\priya\AppData\Local\Temp\ipykernel_28048\3447087411.py:1: SyntaxWarning: invalid escape sequence '\p'
  df=pd.read_csv("C:\priya python\python learning\linear regression\medical_prediction\MedicalInsurancePredictor\Data\medical_insurance.csv")


,age,gender,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520
...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830
1334,18,female,31.920,0,no,northeast,2205.98080
1335,18,female,36.850,0,no,southeast,1629.83350
1336,21,female,25.800,0,no,southwest,2007.94500


### EDA and feature selction

In [ ]:
3.2 gender

In [5]:
df["gender"].value_counts()

gender
male      676
female    662
Name: count, dtype: int64

In [6]:

df["gender"]=df["gender"].map({"male":1,"female":0})
df["gender"].unique()

array([0, 1], dtype=int64)

In [ ]:
3.3 smoker

In [20]:
df["smoker"].value_counts()

smoker
0    1064
1     274
Name: count, dtype: int64

In [19]:
df["smoker"].replace({"yes":1,"no":0},inplace=True)


C:\Users\priya\AppData\Local\Temp\ipykernel_28048\3684056179.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["smoker"].replace({"yes":1,"no":0},inplace=True)
C:\Users\priya\AppData\Local\Temp\ipykernel_28048\3684056179.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["smoker"].replace({

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               1338 non-null   int64  
 1   gender            1338 non-null   int64  
 2   bmi               1338 non-null   float64
 3   children          1338 non-null   int64  
 4   smoker            1338 non-null   int64  
 5   charges           1338 non-null   float64
 6   region_northeast  1338 non-null   int32  
 7   region_northwest  1338 non-null   int32  
 8   region_southeast  1338 non-null   int32  
 9   region_southwest  1338 non-null   int32  
dtypes: float64(2), int32(4), int64(4)
memory usage: 83.8 KB


In [ ]:

3.4 Region

In [12]:
df["region"]

0       southwest
1       southeast
2       southeast
3       northwest
4       northwest
          ...    
1333    northwest
1334    northeast
1335    southeast
1336    southwest
1337    northwest
Name: region, Length: 1338, dtype: object

In [13]:
df=pd.get_dummies(df,columns=["region"],dtype=int)
df

,age,gender,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,yes,16884.92400,0,0,0,1
1,18,1,33.770,1,no,1725.55230,0,0,1,0
2,28,1,33.000,3,no,4449.46200,0,0,1,0
3,33,1,22.705,0,no,21984.47061,0,1,0,0
4,32,1,28.880,0,no,3866.85520,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
1333,50,1,30.970,3,no,10600.54830,0,1,0,0
1334,18,0,31.920,0,no,2205.98080,1,0,0,0
1335,18,0,36.850,0,no,1629.83350,0,0,1,0
1336,21,0,25.800,0,no,2007.94500,0,0,0,1


In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               1338 non-null   int64  
 1   gender            1338 non-null   int64  
 2   bmi               1338 non-null   float64
 3   children          1338 non-null   int64  
 4   smoker            1338 non-null   object 
 5   charges           1338 non-null   float64
 6   region_northeast  1338 non-null   int32  
 7   region_northwest  1338 non-null   int32  
 8   region_southeast  1338 non-null   int32  
 9   region_southwest  1338 non-null   int32  
dtypes: float64(2), int32(4), int64(3), object(1)
memory usage: 83.8+ KB


### 4.feature selction

In [22]:
df.corr()

,age,gender,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
age,1.000000,-0.020856,0.109272,0.042469,-0.025019,0.299008,0.002475,-0.000407,-0.011642,0.010016
gender,-0.020856,1.000000,0.046371,0.017163,0.076185,0.057292,-0.002425,-0.011156,0.017117,-0.004184
bmi,0.109272,0.046371,1.000000,0.012759,0.003750,0.198341,-0.138156,-0.135996,0.270025,-0.006205
children,0.042469,0.017163,0.012759,1.000000,0.007673,0.067998,-0.022808,0.024806,-0.023066,0.021914
smoker,-0.025019,0.076185,0.003750,0.007673,1.000000,0.787251,0.002811,-0.036945,0.068498,-0.036945
charges,0.299008,0.057292,0.198341,0.067998,0.787251,1.000000,0.006349,-0.039905,0.073982,-0.043210
region_northeast,0.002475,-0.002425,-0.138156,-0.022808,0.002811,0.006349,1.000000,-0.320177,-0.345561,-0.320177
region_northwest,-0.000407,-0.011156,-0.135996,0.024806,-0.036945,-0.039905,-0.320177,1.000000,-0.346265,-0.320829
region_southeast,-0.011642,0.017117,0.270025,-0.023066,0.068498,0.073982,-0.345561,-0.346265,1.000000,-0.346265
region_southwest,0.010016,-0.004184,-0.006205,0.021914,-0.036945,-0.043210,-0.320177,-0.320829,-0.346265,1.000000


In [23]:
df.corr().loc[["charges"],:]

,age,gender,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
charges,0.299008,0.057292,0.198341,0.067998,0.787251,1.0,0.006349,-0.039905,0.073982,-0.04321


In [ ]:
VIF

In [63]:
!pip install statsmodels

   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.8 MB 4.0 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.8 MB 3.8 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.8 MB 4.1 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.8 MB 4.2 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.8 MB 4.3 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.8 MB 3.9 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.8 MB 3.9 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.8 MB 3.8 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.8 MB 3.7 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 3.7 MB/s eta 0:00:01
   -----------------------

In [24]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [25]:
x=df.drop("charges",axis=1)
vif_values=[]
for i in range(x.shape[1]):
    vif_value=variance_inflation_factor(x.values,i)
    vif_values.append(vif_value)


In [18]:
s1=pd.Series(vif_values,index=x.columns)
s1

age                  1.016822
gender               1.008900
bmi                  1.106630
children             1.004011
smoker               1.012074
region_northeast     8.603069
region_northwest     8.636205
region_southeast    11.535195
region_southwest     9.218449
dtype: float64

In [ ]:
Model traning


In [28]:
x=df.drop("charges",axis=1)
y=df["charges"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0,shuffle=True)
# y_test

In [42]:
lin_reg_model=LinearRegression()
lin_reg_model.fit(x_train,y_train)

LinearRegression()

In [43]:
# Training Data Evaluation
y_pred_train=lin_reg_model.predict(x_train)
MSE=mean_squared_error(y_train,y_pred_train)
print("MSE",MSE)

MAE=mean_absolute_error(y_train,y_pred_train)
print("MAE:",MAE)

RMSE=np.sqrt(MSE)
print("RMSE:",RMSE)
R2_value=r2_score(y_train,y_pred_train)
print(R2_value)

MSE 37701533.128629126
MAE: 4234.551143314701
RMSE: 6140.157418880165
0.7370262574551634


In [22]:
# Testing data Evaluation
y_pred_test=lin_reg_model.predict(x_test)
MSE=mean_squared_error(y_test,y_pred_test)
print("MSE:",MSE)

RMSE=np.sqrt(MSE)
print("RMSE:",RMSE)

MAE=mean_absolute_error(y_test,y_pred_test)
print("MAE:",MAE)

R2_value=r2_score(y_test,y_pred_test)
print("R2_value",R2_value)

MSE: 31827950.229523823
RMSE: 5641.626558850189
MAE: 3933.272649405236
R2_value 0.7999876970680435


In [ ]:
Testing on user data

In [32]:
x_train[1:2]

,age,gender,bmi,children,smoker,region_northeast,region_northwest,region_southeast,region_southwest
194,18,1,34.43,0,0,0,0,1,0


In [33]:
x_train.shape

(1070, 9)

In [34]:
age=24
gender="female"
bmi=38.22
childeren=2
smoker="no"
region="northwest"


In [35]:
x_train.columns

Index(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')

In [36]:
region="northwest"
region=f"region_{region}"
region

'region_northwest'

In [37]:
test_array=np.zeros((1,x_train.shape[1]))
test_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
y_pred_test=lin_reg_model.predict(test_array)
y_pred_test

c:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-12311.91360565])

In [45]:
x_train.head(1)

,age,gender,bmi,children,smoker,region_northeast,region_northwest,region_southeast,region_southwest
621,37,1,34.1,4,1,0,0,0,1


In [46]:
lab_enc_code={"smoker":{"yes":1,"no":0},
              "gender":{"male":1,"female":0}}
column_names=list(x_train.columns)
print(column_names)

['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast', 'region_northwest', 'region_southeast', 'region_southwest']


In [49]:
age=24
gender="female"
bmi=38.22
children=2
smoker="no"
region="northwest"


In [50]:
test_array[0,0]=age
test_array[0,1]=lab_enc_code["gender"][gender]
test_array[0,2]=bmi
test_array[0,3]=children
test_array[0,4]=lab_enc_code["smoker"][smoker]

region="southeast"
region=f"region_{region}"
region_index=column_names.index(region)
print("region_index:",region_index)
test_array[0,region_index]=1
test_array

region_index: 7


array([[24.  ,  0.  , 38.22,  2.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ]])

In [51]:
prediction=lin_reg_model.predict(test_array)[0]
print("predicted price is:",np.around(prediction,3))

predicted price is: 7061.779


c:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [52]:
with open("lin_reg_model.pkl","wb") as f:
    pickle.dump(lin_reg_model,f)

In [53]:
lab_enc_code={"smoker":{"yes":1,"no":0},
              "gender":{"male":1,"female":0}}
with open("lab_enc_code.json","w") as f:
    json.dump(lab_enc_code,f)